### ISSUE TITLE
[Bug]: Intergrating the node server and frontend for login and signup

### ISSUE THREAD

**Issue by Latish705** [AppointNext/AppointNext#10]
### Contact Details

latishadwani705@gmail.com

### What happened?

As we are migrating from django to node server so integrating the frontend to node server

### Are you interested in contributing?

- [ ] I'd like to work on this issue

### Code of Conduct

- [X] I have used the search function to check if an issue already exists
- [X] I agree to follow this project's Code of Conduct

### Which program are you contributing in?

vsoc

**Comment by aayushdhiman01** [comment]
I would like to work on this,

**Comment by Latish705** [comment]
@aayushdhiman01 we have integrate signup signin of both doctor and patient go ahead assigning it to you

**Comment by Latish705** [comment]
@aayushdhiman01 the node server is in initialze stage ask if you need help with it on discord or here

**Comment by aayushdhiman01** [comment]
@Latish705 ok will ask on discord

**Comment by aayushdhiman01** [comment]
@Latish705 i need some help in connecting to db, do i have to create a local .db file for sqlite or there already some file present in django for database? db.sqlite3 is not accessable unsupported text encoding..

**Comment by Latish705** [comment]
@aayushdhiman01 there is already db file for django but you are working on issue for node server so in node server we are going to use MongoDB the models are like that
