### ISSUE TITLE
[Bug]: In SignUp Doctor button not working also bad structuring of Docter Form

### ISSUE THREAD

**Issue by AkshatPandey-2004** [AppointNext/AppointNext#15]
### Contact Details

akshatpandey26.2004@gmail.com

### What happened?

In SignUp Doctor button is not working also bad structuring of Docter Form
![issue](https://github.com/AppointNext/AppointNext/assets/114497044/ce903d81-71a8-4467-be87-269a345c1c0f)

### What browsers are you seeing the problem on?

Chrome

### Are you interested in contributing?

- [X] I'd like to work on this issue

### Code of Conduct

- [X] I have used the search function to check if an issue already exists
- [X] I agree to follow this project's Code of Conduct

### Which program are you contributing in?

vsoc

**Comment by Latish705** [comment]
@AkshatPandey-2004 what is you idea to fix that
