### ISSUE TITLE
made login and signup button more attractive

### ISSUE THREAD

**Issue by Krishna100604** [AppointNext/appointnext#20]
### Is your feature request related to a problem? Please describe.

@Latish705 assign me this under vsoc'24

### Describe the solution you'd like

![Screenshot (128)](https://github.com/AppointNext/AppointNext/assets/110299021/fca4b589-12e9-4af5-b586-a7791b4980be)
![Screenshot (126)](https://github.com/AppointNext/AppointNext/assets/110299021/1eddeae0-5eae-4480-9950-fe471d3a90ca)
![Screenshot (129)](https://github.com/AppointNext/AppointNext/assets/110299021/bb4b1f4f-8f68-48cf-8ba3-4bb39a313364)

### Are you interested in contributing?

- [X] I'd like to work on this issue

### Code of Conduct

- [X] I have used the search function to check if an issue already exists
- [X] I agree to follow this project's Code of Conduct

### Which program are you contributing in?

Not applicable

**Comment by Latish705** [comment]
@Krishna100604 what you are planning to do

**Comment by Krishna100604** [comment]
> @Krishna100604 what you are planning to do

changed the style of login and sign up button and in the sin up page and sign in page made the changes

**Comment by MrinmayiVerma** [comment]
Can I work on This issue

**Comment by Krishna100604** [comment]
> Can I work on This issue

i think this is over it is about 3 months ago

**Comment by Krishna100604** [comment]
@MrinmayiVerma if you want to work on the project you can go to my github and fork eduverse-app project and try to make that website responsive for all screen

**Comment by MrinmayiVerma** [comment]
Okay I will start working on it

**Comment by Krishna100604** [comment]
@MrinmayiVerma  to contact me u can dm me on discord  , Id is srp04_

**Comment by MrinmayiVerma** [comment]
I send a friend request
