### ISSUE TITLE
[Feature]: Enhancement of Homepage UI

### ISSUE THREAD

**Issue by Mehak-Mattoo** [AppointNext/AppointNext#23]
### Is your feature request related to a problem? Please describe.

The current UI does not work for all medias. The text should change according to screen sizes. 

### Describe the solution you'd like

I would like to use Tailwind to introduce easier responsiveness in the website. 

### Alternatives

If tailwind doesn't work, i can use bootstrap classes. 

### Additional Context

I will be working under the program VSOC24, so you can assign me this issue under that. 

### Are you interested in contributing?

- [X] I'd like to work on this issue

### Code of Conduct

- [X] I have used the search function to check if an issue already exists
- [X] I agree to follow this project's Code of Conduct

### Which program are you contributing in?

Not applicable

**Comment by Latish705** [comment]
@Mehak-Mattoo closing this another issue #18 is raised for it
