### ISSUE TITLE
[Feature]: Adding a 404 page

### ISSUE THREAD

**Issue by Mehak-Mattoo** [AppointNext/AppointNext#24]
### Is your feature request related to a problem? Please describe.

Adding a custom 404 page can help users navigate to a certain page if they entered into a wrong page. 

### Describe the solution you'd like

I would create a custom animated 404 page that will negate the user frustration and can redirect them back to the homepage 

### Additional Context

Can you assign me this issue under VSOC 24

### Are you interested in contributing?

- [X] I'd like to work on this issue

### Code of Conduct

- [X] I have used the search function to check if an issue already exists
- [X] I agree to follow this project's Code of Conduct

### Which program are you contributing in?

Not applicable

**Comment by Latish705** [comment]
@Mehak-Mattoo do you have any design idea , if then showcase for now I assigning it to you are participating under any program

**Comment by Mehak-Mattoo** [comment]
Yes, here is my inspiration


https://github.com/AppointNext/AppointNext/assets/77096365/911eb6dc-5932-4afc-8257-dc90e550a2df


But instead of a girl here, i would add a doctor figure with a heading saying - 404 Nobody is allowed here (like a doctor yelling).

Also i think this issue should be tagged medium😅 as it's not a minor task

**Comment by Latish705** [comment]
@Mehak-Mattoo share your email for getting credits for pr

**Comment by Mehak-Mattoo** [comment]
Sure, its mehakmattoo7@gmail.com
