### ISSUE TITLE
[Bug]: Need to improve the responsiveness of footer

### ISSUE THREAD

**Issue by Latish705** [AppointNext/AppointNext#3]
![image](https://github.com/AppointNext/AppointNext/assets/104522651/7cec1ffb-2b1b-48c9-b8bd-0e884a302417)

We could improve the responsive design for footer for mobile

**Comment by SeanAverS** [comment]
Hello, 

I am interested on working on this. Could I please be assigned? Thank you.

**Comment by shivamnarkar47** [comment]
I would like to contribute to it. Please assign it to me.

**Comment by Latish705** [comment]
@shivamnarkar47 go ahead are you participating under any program

**Comment by shivamnarkar47** [comment]
> @shivamnarkar47 go ahead are you participating under any program

Yes VSOC'24
